apiVersion: v1
kind: Service
metadata:
  name: "{{ include "k8s-event-logger.fullname" . }}"
spec:
  selector:
    app: {{ include "k8s-event-logger.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

